config/routes.php
<?php
/**
 * Routes configuration.
 *
 * In this file, you set up routes to your controllers and their actions.
 * Routes are very important mechanism that allows you to freely connect
 * different URLs to chosen controllers and their actions (functions).
 *
 * It's loaded within the context of `Application::routes()` method which
 * receives a `RouteBuilder` instance `$routes` as method argument.
 *
 * CakePHP(tm) : Rapid Development Framework (https://cakephp.org)
 * Copyright (c) Cake Software Foundation, Inc. (https://cakefoundation.org)
 *
 * Licensed under The MIT License
 * For full copyright and license information, please see the LICENSE.txt
 * Redistributions of files must retain the above copyright notice.
 *
 * @copyright     Copyright (c) Cake Software Foundation, Inc. (https://cakefoundation.org)
 * @link          https://cakephp.org CakePHP(tm) Project
 * @license       https://opensource.org/licenses/mit-license.php MIT License
 */

 use Cake\Http\Middleware\CsrfProtectionMiddleware;
use Cake\Routing\Route\DashedRoute;
use Cake\Routing\RouteBuilder;

/*
 * The default class to use for all routes
 *
 * The following route classes are supplied with CakePHP and are appropriate
 * to set as the default:
 *
 * - Route
 * - InflectedRoute
 * - DashedRoute
 *
 * If no call is made to `Router::defaultRouteClass()`, the class used is
 * `Route` (`Cake\Routing\Route\Route`)
 *
 * Note that `Route` does not do any inflections on URLs which will result in
 * inconsistently cased URLs when used with `:plugin`, `:controller` and
 * `:action` markers.
 */
/** @var \Cake\Routing\RouteBuilder $routes */
$routes->setRouteClass(DashedRoute::class);

$routes->scope('/', function (RouteBuilder $builder) {
    $builder->registerMiddleware('csrf', new CsrfProtectionMiddleware([
        'httponly' => true,
    ]));
    // $builder->applyMiddleware('csrf');
    /*
     * Here, we are connecting '/' (base path) to a controller called 'Pages',
     * its action called 'display', and we pass a param to select the view file
     * to use (in this case, templates/Pages/home.php)...
     */
    $builder->connect('/', ['controller' => 'Pokemons', 'action' => 'index']);

    /*
     * ...and connect the rest of 'Pages' controller's URLs.
     */
    $builder->connect('/pages/*', 'Pages::display');

    /*
     * Connect catchall routes for all controllers.
     *
     * The `fallbacks` method is a shortcut for
     *
     * ```
     * $builder->connect('/:controller', ['action' => 'index']);
     * $builder->connect('/:controller/:action/*', []);
     * ```
     *
     * You can remove these routes once you've connected the
     * routes you want in your application.
     */
    $builder->fallbacks();
});



/*
 * If you need a different set of middleware or none at all,
 * open new scope and define routes there.
 *
 * ```
 * $routes->scope('/api', function (RouteBuilder $builder) {
 *     // No $builder->applyMiddleware() here.
 *     
 *     // Parse specified extensions from URLs
 *     // $builder->setExtensions(['json', 'xml']);
 *     
 *     // Connect API actions here.
 * });
 * ```
 */

src/Model/Entity/Pokemon.php
<?php
declare(strict_types=1);

namespace App\Model\Entity;

use Cake\ORM\Entity;

/**
 * Pokemon Entity
 *
 * @property int $id
 * @property string $name
 * @property int $height
 * @property int $weight
 * @property string $default_front_sprite_url
 * @property \Cake\I18n\FrozenTime $created
 * @property \Cake\I18n\FrozenTime $modified
 *
 * @property \App\Model\Entity\PokemonStat[] $pokemon_stats
 * @property \App\Model\Entity\PokemonType[] $pokemon_types
 */
class Pokemon extends Entity
{
    /**
     * Fields that can be mass assigned using newEntity() or patchEntity().
     *
     * Note that when '*' is set to true, this allows all unspecified fields to
     * be mass assigned. For security purposes, it is advised to set '*' to false
     * (or remove it), and explicitly make individual fields accessible as needed.
     *
     * @var array
     */
    protected $_accessible = [
        '*' => true,
        'id' => false,
    ];


    /**
     * Undocumented function
     *
     * @return string
     */
    protected function _getMainSprite()
    {
        return $this->default_front_sprite_url ? $this->default_front_sprite_url : 'unknown.png';
    }

    /**
     * Return the first type for a pokemon
     *
     * @return string
     */
    protected function _getFirstType()
    {
        if (isset($this->pokemon_types) && !empty($this->pokemon_types)) {
            return collection($this->pokemon_types)
                ->extract('type.name')
                ->first();
        }

        return 'normal';
    }

    /**
     * Return the first type for a pokemon
     *
     * @return string
     */
    protected function _getSecondType()
    {
        if (isset($this->pokemon_types) && !empty($this->pokemon_types)) {
            return collection($this->pokemon_types)
                ->extract('type.name')
                ->skip(1)
                ->first();
        }

        return 'normal';
    }

    protected function _getHasSecondType()
    {
        if (isset($this->pokemon_types) && !empty($this->pokemon_types)) {
            return collection($this->pokemon_types)->count() > 1;
        }

        return false;
    }
}

src/Model/Entity/PokemonType.php
<?php
declare(strict_types=1);

namespace App\Model\Entity;

use Cake\ORM\Entity;

/**
 * PokemonType Entity
 *
 * @property int $id
 * @property string $pokemon_id
 * @property string $type_id
 * @property \Cake\I18n\FrozenTime $created
 * @property \Cake\I18n\FrozenTime $modified
 *
 * @property \App\Model\Entity\Pokemon $pokemon
 * @property \App\Model\Entity\Type $type
 */
class PokemonType extends Entity
{
    /**
     * Fields that can be mass assigned using newEntity() or patchEntity().
     *
     * Note that when '*' is set to true, this allows all unspecified fields to
     * be mass assigned. For security purposes, it is advised to set '*' to false
     * (or remove it), and explicitly make individual fields accessible as needed.
     *
     * @var array
     */
    protected $_accessible = [
        '*' => true,
        'id' => false,
    ];
}

src/Model/Table/PokemonsTable.php
<?php
declare(strict_types=1);

namespace App\Model\Table;

use Cake\ORM\Query;
use Cake\ORM\RulesChecker;
use Cake\ORM\Table;
use Cake\Validation\Validator;

/**
 * Pokemons Model
 *
 * @property \App\Model\Table\PokemonStatsTable&\Cake\ORM\Association\HasMany $PokemonStats
 * @property \App\Model\Table\PokemonTypesTable&\Cake\ORM\Association\HasMany $PokemonTypes
 *
 * @method \App\Model\Entity\Pokemon newEmptyEntity()
 * @method \App\Model\Entity\Pokemon newEntity(array $data, array $options = [])
 * @method \App\Model\Entity\Pokemon[] newEntities(array $data, array $options = [])
 * @method \App\Model\Entity\Pokemon get($primaryKey, $options = [])
 * @method \App\Model\Entity\Pokemon findOrCreate($search, ?callable $callback = null, $options = [])
 * @method \App\Model\Entity\Pokemon patchEntity(\Cake\Datasource\EntityInterface $entity, array $data, array $options = [])
 * @method \App\Model\Entity\Pokemon[] patchEntities(iterable $entities, array $data, array $options = [])
 * @method \App\Model\Entity\Pokemon|false save(\Cake\Datasource\EntityInterface $entity, $options = [])
 * @method \App\Model\Entity\Pokemon saveOrFail(\Cake\Datasource\EntityInterface $entity, $options = [])
 * @method \App\Model\Entity\Pokemon[]|\Cake\Datasource\ResultSetInterface|false saveMany(iterable $entities, $options = [])
 * @method \App\Model\Entity\Pokemon[]|\Cake\Datasource\ResultSetInterface saveManyOrFail(iterable $entities, $options = [])
 * @method \App\Model\Entity\Pokemon[]|\Cake\Datasource\ResultSetInterface|false deleteMany(iterable $entities, $options = [])
 * @method \App\Model\Entity\Pokemon[]|\Cake\Datasource\ResultSetInterface deleteManyOrFail(iterable $entities, $options = [])
 *
 * @mixin \Cake\ORM\Behavior\TimestampBehavior
 */
class PokemonsTable extends Table
{
    /**
     * Initialize method
     *
     * @param array $config The configuration for the Table.
     * @return void
     */
    public function initialize(array $config): void
    {
        parent::initialize($config);

        $this->setTable('pokemons');
        $this->setDisplayField('name');
        $this->setPrimaryKey('id');

        $this->addBehavior('Timestamp');

        $this->hasMany('PokemonStats', [
            'foreignKey' => 'pokemon_id',
            'saveStrategy' => 'replace',
        ]);
        $this->hasMany('PokemonTypes', [
            'foreignKey' => 'pokemon_id',
            'saveStrategy' => 'replace',
        ]);
    }

    /**
     * Default validation rules.
     *
     * @param \Cake\Validation\Validator $validator Validator instance.
     * @return \Cake\Validation\Validator
     */
    public function validationDefault(Validator $validator): Validator
    {
        $validator
            ->integer('id')
            ->allowEmptyString('id', null, 'create');

        $validator
            ->scalar('name')
            ->maxLength('name', 255)
            ->requirePresence('name', 'create')
            ->notEmptyString('name');

        $validator
            ->integer('height')
            ->requirePresence('height', 'create')
            ->notEmptyString('height');

        $validator
            ->integer('weight')
            ->requirePresence('weight', 'create')
            ->notEmptyString('weight');

        $validator
            ->scalar('default_front_sprite_url')
            ->maxLength('default_front_sprite_url', 255)
            ->allowEmptyString('default_front_sprite_url');

        $validator
            ->scalar('default_back_sprite_url')
            ->maxLength('default_back_sprite_url', 255)
            ->allowEmptyString('default_back_sprite_url');  
            
        $validator
            ->scalar('shiny_front_sprite_url')
            ->maxLength('shiny_front_sprite_url', 255)
            ->allowEmptyString('shiny_front_sprite_url');
 

        return $validator;
    }

    /**
     * Format Data for save
     *
     * @param array $pokeApiData Data from Poke Api
     * @return array
     */
    public function formatDataForSave($pokeApiData)
    {
        $pokemonStats = $this->PokemonStats->formatDataForSave($pokeApiData['stats']);
        $pokemonTypes = $this->PokemonTypes->formatDataForSave($pokeApiData['types']);

        return [
            'pokedex_number' => $pokeApiData['id'],
            'name' => $pokeApiData['name'],
            'default_front_sprite_url' => $pokeApiData['sprites']['front_default'],
            'default_back_sprite_url' => $pokeApiData['sprites']['back_default'],
            'shiny_front_sprite_url' => $pokeApiData['sprites']['front_shiny'],
            'height' => $pokeApiData['height'],
            'weight' => $pokeApiData['weight'],
            'pokemon_stats' => $pokemonStats,
            'pokemon_types' => $pokemonTypes,
        ];
    }
}

src/Controller/PokemonsController.php
<?php

declare(strict_types=1);

namespace App\Controller;

/**
 * Pokemons Controller
 *
 * @property \App\Model\Table\PokemonsTable $Pokemons
 * @method \App\Model\Entity\Pokemon[]|\Cake\Datasource\ResultSetInterface paginate($object = null, array $settings = [])
 */
class PokemonsController extends AppController
{
    /**
     * Index method
     *
     * @return \Cake\Http\Response|null|void Renders view
     */
    public function index()
    {
        $this->paginate = [
            'limit' => 30,
        ];

        $pokemons = $this->Pokemons->find('all')->contain(['PokemonStats.Stats', 'PokemonTypes.Types']);
        $pokemons = $this->paginate($pokemons);

        $this->set(compact('pokemons'));
    }

    /**
     * View method
     *
     * @param string|null $id Pokemon id.
     * @return \Cake\Http\Response|null|void Renders view
     * @throws \Cake\Datasource\Exception\RecordNotFoundException When record not found.
     */
    public function view($id = null)
    {
        $pokemon = $this->Pokemons->get($id, [
            'contain' => ['PokemonStats.Stats', 'PokemonTypes.Types'],
        ]);

        $this->set(compact('pokemon'));
    }

    /**
     * Delete method
     *
     * @param string|null $id Pokemon id.
     * @return \Cake\Http\Response|null|void Redirects to index.
     * @throws \Cake\Datasource\Exception\RecordNotFoundException When record not found.
     */
    public function delete($id = null)
    {
        $this->request->allowMethod(['post', 'delete']);
        $pokemon = $this->Pokemons->get($id);
        if ($this->Pokemons->delete($pokemon)) {
            $this->Flash->success(__('The pokemon has been deleted.'));
        } else {
            $this->Flash->error(__('The pokemon could not be deleted. Please, try again.'));
        }

        return $this->redirect(['action' => 'index']);
    }

    /**
     * Dashboard method
     *
     * @return \Cake\Http\Response|null|void Renders view
     */
    public function dashboard()
    {

        $pokemons = $this->Pokemons->find('all')->contain(['PokemonStats.Stats', 'PokemonTypes.Types']);
        $this->set(compact('pokemons'));
    }
}

templates/Pokemons/dashboard.php
<?php
/**
 * @var \App\View\AppView $this
 */
use Cake\ORM\TableRegistry;
?>
<div class="pokemons" align="center">
    <br>
    <h3 align="center"><?= __('Dashboard') ?></h3>
    <div style="margin-right:2%;margin-left:2%;">
        <table>
            <tr style="background-color:rgb(220, 220, 220);">
                <td width=1%></td>
                <td width=45% style="border-color:white;">Poid moyen des pokemons de la 4G (en kg*10)</td>
                <td style="border-color:white;" width=auto>
                    <?php
                        $début=387;
                        $fin=493;
                        $somme=0;
                        $count=0;
                        for($i=$début;$i<=$fin;$i++){
                            $parcour = TableRegistry::getTableLocator()->get('pokemons')->find()->where(["pokedex_number = $i"]);
                            foreach($parcour as $poid){
                                $somme=$somme+ $poid->weight;
                            }
                            $count+=1;
                        }
                    echo round($somme/$count,2);
                    ?>
                </td>
                <td width=1% border=none></td>
            </tr>
            <tr style="background-color:rgb(207, 207, 207);">
                <td width=1%></td>
                <td width=45% style="border-color:white;">Nombre de pokemons fée dans les génération 1,3 et 7</td>
                <td style="border-color:white;">
                    <?php
                        $début=1;
                        $fin=809;
                        $count=0;
                        for($i=$début;$i<=$fin;$i++){
                            if(($i>0 AND $i<152) OR ($i>253 AND $i<385) OR ($i>721 AND $i<810)){
                                $tri = TableRegistry::getTableLocator()->get('pokemon_types')->find()->where(["pokemon_id = $i"]);
                                foreach($tri as $trier){
                                    $type = TableRegistry::getTableLocator()->get('types')->find()->where(["id = $trier->type_id"]);
                                    foreach($type as $types){
                                        if($types->name=='fairy'){
                                            $count+=1;
                                        }
                                    }
                                }
                            }
                        }
                        echo $count;
                    ?>
                </td>
                <td width=1% border=none></td>
            </tr>
            <tr style="background-color:rgb(197, 197, 197);">
                <td width=1%></td>
                <td width=45%>10 premier pokemons les plus rapide</td>
                <td>
                    <?php
                        $début=1;
                        $fin=898;
                        $compte=0;
                        for($i=$début;$i<=$fin;$i++)
                        {
                            $trivit = TableRegistry::getTableLocator()->get('pokemon_stats')->find()->where(["stat_id = 6"])->order(["value" => "DESC"]);
                            foreach($trivit as $vitesse){
                                if($compte<10){
                                    $vite=TableRegistry::getTableLocator()->get('pokemons')->find()->where(["id=$vitesse->pokemon_id"]);
                                    ?>
                                    <table>
                                        <?php
                                            foreach($vite as $rapide){
                                        ?>
                                                <tr class="type--<?php
                                                    $firstcolor=true;
                                                    $recuptypes = TableRegistry::getTableLocator()->get('pokemon_types')->find()->where(["pokemon_id=$rapide->id"]);
                                                    foreach($recuptypes as $types){
                                                        $couleurtypes = TableRegistry::getTableLocator()->get('types')->find()->where(["id=$types->type_id"]);
                                                        foreach($couleurtypes as $couleur){
                                                            if($firstcolor){
                                                                $firstcolor=false;
                                                                echo $couleur->name;
                                                            }
                                                        }
                                                    }
                                                ?>">
                                                    <td style="border-color:rgb(97, 97, 97);" width=1%></td>
                                                    <td style="border-color:rgb(97, 97, 97);" width=15%>
                                                        <?php
                                                            echo $compte+1;
                                                        ?>
                                                    </td>
                                                    <td style="border-color:rgb(97, 97, 97);" width=30%><?php echo $rapide->pokedex_number ?></td>
                                                    <td style="border-color:rgb(97, 97, 97);" width=30%>
                                                        <?= $this->Html->link(__(ucwords($rapide->name)), ['controller' => 'Pokemons','action' => 'view', $rapide->id], ['class' => "nav-link"]); ?>
                                                    </td>
                                                    <td style="border-color:rgb(97, 97, 97);" width=25%>
                                                        <img src="<?= $rapide->default_front_sprite_url ?>" alt="default sprite" width="90%">
                                                    </td>
                                                </tr>
                                        <?php
                                            }
                                            $compte+=1;
                                        ?>
                                    </table>
                                    <?php
                                }
                            }
                        }       ?>
                </td>
                <td border=none></td>
            </tr>
        </table>
        <br>
    </div>
</div>

templates/Pokemons/index.php
<?php
/**
 * @var \App\View\AppView $this
 * @var \App\Model\Entity\Pokemon[]|\Cake\Collection\CollectionInterface $pokemons
 */
?>
<div class="pokemons index content">
    <h3 align="center"><?= __('Pokemons') ?></h3>

    <div class="row">
        <?php foreach ($pokemons as $pokemon) : ?>
                <div class="col-12 col-md-4 col-sm-6 col-xs-12">
                    <?= $this->element('Pokemons/card', ['pokemon' => $pokemon]); ?>
                </div>
        <?php endforeach; ?>
    </div>
    <div class="paginator">
        <ul class="pagination">
            <?= $this->Paginator->first('<< ' . __('first')) ?>
            <?= $this->Paginator->prev('< ' . __('previous')) ?>
            <?= $this->Paginator->numbers() ?>
            <?= $this->Paginator->next(__('next') . ' >') ?>
            <?= $this->Paginator->last(__('last') . ' >>') ?>
        </ul>
        <p><?= $this->Paginator->counter(__('Page {{page}} of {{pages}}, showing {{current}} record(s) out of {{count}} total')) ?></p>
    </div>
</div>

templates/Pokemons/view.php
<?php
/**
 * @var \App\View\AppView $this
 * @var \App\Model\Entity\Pokemon $pokemon
 */
use Cake\ORM\TableRegistry;
?>
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.1/css/bootstrap.min.css">
<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.1/js/bootstrap.min.js"></script>
<div>
    <div class="column-responsive column-80">
        <div class="pokemons view content" style="margin-left:10%; margin-right:10%;">
            <h3 class="PokeName" align="center"><?= h($pokemon->name) ?></h3>
            <div id="myCarousel" class="carousel slide" data-ride="carousel" data-interval="false">
                <div class="carousel-inner"">
                    <?php if(!empty($pokemon->shiny_front_sprite_url)){ ?>
                        <div class="item" align="center">
                            <img src="<?= h($pokemon->shiny_front_sprite_url) ?>" alt="Default" width="40%">
                        </div>
                    <?php } else{ ?>
                        <div class="item" align="center" style="margin-top:15%; margin-bottom:20.25%">
                            <img src="<?= h($pokemon->shiny_front_sprite_url) ?>" alt="Shiny" width="40%">
                        </div>
                    <?php } ?>
                    <?php if(!empty($pokemon->default_front_sprite_url)){ ?>
                        <div class="item active" align="center">
                            <img src="<?= h($pokemon->default_front_sprite_url) ?>" alt="Default" width="40%">
                        </div>
                    <?php } else{ ?>
                        <div class="item active" align="center" style="margin-top:15%; margin-bottom:20.25%">
                            <img src="<?= h($pokemon->default_front_sprite_url) ?>" alt="Default" width="40%">
                        </div>
                    <?php } ?>
                    <?php if(!empty($pokemon->default_back_sprite_url)){ ?>
                        <div class="item" align="center">
                            <img src="<?= h($pokemon->default_back_sprite_url) ?>" alt="Default" width="40%">
                        </div>
                    <?php } else{ ?>
                        <div class="item" align="center" style="margin-top:15%; margin-bottom:20.25%">
                            <img src="<?= h($pokemon->default_back_sprite_url) ?>" alt="Back" width="40%">
                        </div>
                    <?php } ?>
                </div>

                <a class="left carousel-control" href="#myCarousel" data-slide="prev" style="background:rgb(228, 228, 228);">
                    <span class="glyphicon glyphicon-arrow-left"></span>
                </a>
                <a class="right carousel-control" href="#myCarousel" data-slide="next" style="background:rgb(228, 228, 228);">
                    <span class="glyphicon glyphicon-arrow-right"></span>
                </a>
            </div>
            <br>
            <div class="color_type1" align="left"><table class="types" border="2"><tr><td class="type--<?= h($pokemon->first_type) ?>"><?= h($pokemon->first_type) ?></td></tr></table></div>
            <?php if ($pokemon->has_second_type) : ?>
                <div class="color_type2" align="right"><table class="types" border="2"><tr><td class="type--<?= h($pokemon->second_type) ?>"><?= $pokemon->second_type ?></td></tr></table></div>
            <?php endif ?>
            <br>
            <br>
            <div class="related">
                <?php if (!empty($pokemon->pokemon_stats)) : ?>
                    <div class="table-responsive">
                        <table class="stats" border="5">
                            <?php foreach ($pokemon->pokemon_stats as $pokemonStats) : ?>
                                <tr>
                                    <?php
                                        $requete = TableRegistry::getTableLocator()->get('stats')->find()->where(["id = $pokemonStats->stat_id"]);
                                        foreach ($requete as $stats) { ?>
                                            <td class="types"><?php echo $stats->name;?></td>
                                            <td class="types"><?= h($pokemonStats->value) ?></td>
                                    <?php }  ?>
                                </tr>
                            <?php endforeach; ?>
                        </table>
                    </div>
                <?php endif; ?>
            </div>
        </div>
    </div>
</div>